# Generated by Django 2.2.3 on 2022-03-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='headimg',
            field=models.FileField(blank=True, null=True, upload_to='img/'),
        ),
    ]
