# Generated by Django 2.2.3 on 2022-03-13 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_headimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
