# Generated by Django 2.2.3 on 2022-03-14 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0005_user_headimg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='headimg',
            field=models.ImageField(default='avatars/default.jpg', upload_to='avatars/'),
        ),
    ]
