# Generated by Django 2.2.3 on 2022-03-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0014_auto_20220327_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.FileField(upload_to='avatar/'),
        ),
    ]
